### ISSUE TITLE
New Function: `age_at_date`

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/phsmethods#65]
As per this [chat on Teams](https://teams.microsoft.com/l/message/19:9620ef6cf8234d50a0f95caba65a3edf@thread.tacv2/1624031770131?tenantId=10efe0bd-a030-4bca-809c-b5e6745e499a&groupId=ec4250f9-b70a-4f32-9372-a232ccb4f713&parentMessageId=1624031770131&teamName=PHS%20R%20User%20Group&channelName=Technical%20Queries&createdTime=1624031770131), there are numerous possible options for calculating age. 

It would be good to have a simple function that takes dob and a date and returns the age in years. I could be wrong but I don't think there's a need for age in months, days or factional years? Definitely, whole years should be the default, if not the only option.

The function would need to be tested against all edge cases (combination of leap year dates etc.) to validate the methodology and tested against existing options for speed. It's possible just a wrapper to simplify an existing function would be the most efficient, e.g.

```R
age_at_date <- function(dob, date) {
  #Test for date type supplied...

  #Return age at date in years
  age <- lubridate::as.period(lubridate::interval(dob, date))$year
  return(age)
}

**Comment by davidc92** [comment]
I'm disinclined to greenlight this when `age_calc` from `eeptools` already does this in days, months and years. It might be a little slower when a vector is supplied rather than a single date, but we are talking milliseconds rather than minutes or even hours. I don't think that speed gain is worth the effort this would take to do properly. Especially when this function already handles leap years quite nicely.

**Comment by Nic-Chr** [comment]
I like the idea of a having a function to calculate age, especially using `lubridate` functions.
The two things I'm not a big of fan of with `eeptools::age_calc` are how you sometimes get a returned numeric class and other times a difftime class (see below for an example).

```{r}
> my_date <- lubridate::dmy("29022020")
> eeptools::age_calc(my_date, units = "days")
Time difference of 489 days
> eeptools::age_calc(my_date, units = "years")
[1] 1.336986
```

The second thing I don't like is how units more granular than days aren't supported, but I'm sure this was intentional.

```{r}
> eeptools::age_calc(my_date, units = "hours")
Error in eeptools::age_calc(my_date, units = "hours") : 
  Unrecognized units. Please choose years, months, or days.
```

Perhaps we could use something like below which has similar general functionality as `eeptools::age_calc` though I do appreciate that the functionality of having granular time units may not be necessary.

```{r}
> age_at_date <- function(dob, end_date = Sys.time(), units = "years", round_down = TRUE) {
+   unit_duration <- lubridate::duration(num = 1, units = units)
+   age_interval <- lubridate::interval(dob, end_date)
+   if (round_down) {
+     age_interval %/% unit_duration
+   } else {
+     age_interval / unit_duration
+   }
+ }
> 
> age_at_date(my_date, units = "years")
[1] 1
> age_at_date(my_date, units = "months")
[1] 16
> age_at_date(my_date, units = "days")
[1] 489
> age_at_date(my_date, units = "hours")
[1] 11745
> age_at_date(my_date, units = "minutes")
[1] 704759
> age_at_date(my_date, units = "seconds")
[1] 42285555
> age_at_date(my_date, units = "years", round_down = FALSE)
[1] 1.339948
> age_at_date(my_date, units = "months", round_down = FALSE)
[1] 16.07938
> age_at_date(my_date, units = "days", round_down = FALSE)
[1] 489.4161
> age_at_date(my_date, units = "hours", round_down = FALSE)
[1] 11745.99
> age_at_date(my_date, units = "minutes", round_down = FALSE)
[1] 704759.3
> age_at_date(my_date, units = "seconds", round_down = FALSE)
[1] 42285555
```

**Comment by Moohan** [comment]
That's quite a nice implementation Nic.

@davidc92 I'd say the main reason would be to provide an obvious function to use i.e. "Use the one in phsmethods" whilst eeptools does do what we want I wasn't aware of it before now so I'd guess other people aren't either (seems to be the case from the original Teams thread too).
